### ISSUE TITLE
Einsatz als Filter im Backend nicht möglich

### ISSUE THREAD

**Issue by pandroid** [MetaModels/attribute_tags#14]
Wenn ich für das Attribut mit dem Feldtyp "tags" die Option "Filterbar" aktiviere, erhalte ich beim Aufruf der Backend-Liste den Fehler

```
Warning: Illegal offset type in system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php on line 159
#0 system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php(159): __error(2, 'Illegal offset ...', '/www/htdocs/w00...', 159, Array)
#1 system/modules/generalDriver/DcGeneral/Panel/DefaultPanel.php(71): DcGeneral\Panel\DefaultFilterElement->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#2 system/modules/generalDriver/DcGeneral/Panel/DefaultPanelContainer.php(70): DcGeneral\Panel\DefaultPanel->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#3 system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1279): DcGeneral\Panel\DefaultPanelContainer->initialize(Object(DcGeneral\Data\DefaultConfig))
#4 system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1294): DcGeneral\Controller\DefaultController->buildPanel()
#5 system/modules/generalDriver/DcGeneral/DC_General.php(2382): DcGeneral\Controller\DefaultController->showAll()
#6 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(176): DcGeneral\DC_General->showAll()
#7 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(196): MetaModels\BackendIntegration\Module->runDC()
#8 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(210): MetaModels\BackendIntegration\Module->performNormal()
#9 system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#10 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_sh...')
#11 contao/main.php(293): Main->run()
#12 {main}
```

**Comment by xantippe** [comment]
getestet in MM alpha10: 
* keine Fehlermeldung
* Filterauswahl erscheint bei Liste
* es wird gefiltert

=> kann m.E. geschlossen werden
