### ISSUE TITLE
Fatal error: Uncaught exception Exception with message Query error...

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_tags#21]
Nach letztem Update gibts nur noch:

```
Fatal error: Uncaught exception Exception with message Query error: Unknown column 'xyz' in 'field list' (SELECT xyz FROM mm_xxx GROUP BY xyz) thrown in system/modules/core/library/Contao/Database/Statement.php on line 283

#0 system/modules/core/library/Contao/Database/Statement.php(254): Contao\Database\Statement->query()
#1 composer/vendor/metamodels/attribute_tags/src/MetaModels/Attribute/Tags/MetaModelTags.php(253): Contao\Database\Statement->execute()
#2 composer/vendor/metamodels/attribute_tags/src/MetaModels/Attribute/Tags/MetaModelTags.php(159): MetaModels\Attribute\Tags\MetaModelTags->buildFilterRulesForUsedOnly(Object(MetaModels\Filter\Filter))
#3 composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/SimpleLookup.php(82): MetaModels\Attribute\Tags\MetaModelTags->getFilterOptions(NULL, true, NULL)
#4 composer/vendor/metamodels/filter_tags/src/MetaModels/Filter/Setting/Tags.php(82): MetaModels\Filter\Setting\SimpleLookup->getParameterFilterOptions(Object(MetaModels\Attribute\Tags\MetaModelTags), NULL)
#5 composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/Collection.php(216): MetaModels\Filter\Setting\Tags->prepareRules(Object(MetaModels\Filter\Filter), Array)
#6 composer/vendor/metamodels/core/src/MetaModels/Filter/Setting/Collection.php(281): MetaModels\Filter\Setting\Collection->addRules(Object(MetaModels\Filter\Filter), Array)
#7 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/FrontendFilter.php(304): MetaModels\Filter\Setting\Collection->getParameterFilterWidgets(Array, Array, Object(MetaModels\FrontendIntegration\FrontendFilterOptions))
#8 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/FrontendFilter.php(91): MetaModels\FrontendIntegration\FrontendFilter->getFilters()
#9 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(59): MetaModels\FrontendIntegration\FrontendFilter->getMetaModelFrontendFilter(Object(MetaModels\FrontendIntegration\Content\Filter))
#10 system/modules/core/classes/Hybrid.php(228): MetaModels\FrontendIntegration\HybridFilterBlock->compile()
#11 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(88): Contao\Hybrid->generate()
#12 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridFilterBlock.php(48): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#13 system/modules/core/library/Contao/Controller.php(468): MetaModels\FrontendIntegration\HybridFilterBlock->generate()
#14 system/modules/core/modules/ModuleArticle.php(196): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#15 system/modules/core/modules/Module.php(163): Contao\ModuleArticle->compile()
#16 system/modules/core/modules/ModuleArticle.php(59): Contao\Module->generate()
#17 system/modules/core/library/Contao/Controller.php(404): Contao\ModuleArticle->generate(false)
#18 system/modules/core/library/Contao/Controller.php(268): Contao\Controller::getArticle(Object(Contao\ArticleModel), true, false, 'main')
#19 system/modules/core/pages/PageRegular.php(138): Contao\Controller::getFrontendModule('0', 'main')
#20 index.php(260): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 index.php(444): Index->run()
#22 {main}
```

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?

**Comment by uagga** [comment]
gleiches Problem wie beschrieben.

**Comment by discordier** [comment]
@uagga Welches Problem tritt bei dir wie beschrieben auf? Keine der hier zitierten Code stellen existiert noch in derselben Version wie zum Zeitpunkt als dieses ticket geoeffnet wurde, weiterhin wurden hier 3 verschiedene Problematiken besprochen.

Bitte mache ein neues Ticket auf mit neuem stack trace und genauen Informationen wie das Problem nachzustellen ist.
