### ISSUE TITLE
Fehlermeldung bei der Zuordnung über Tags aus einem anderen MM

### ISSUE THREAD

**Issue by codesache** [MetaModels/attribute_tags#41]
Hallo zusammen,
Ich bekomme ein Fehlermeldung bei der Zuordnung über Tags aus einem anderen MM im Backend.
In der Fehlermeldung hier ist ein Komma zu viel oder der Wert wird nicht übergeben. 

Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3 (INSERT INTO tl_metamodel_tag_relation (att_id, item_id, value_sorting, value_id) VALUES (64,2,0,)) thrown in C:\xampp\htdocs\xxxxxxx\system\modules\core\library\Contao\Database\Statement.php on line 279

Der Ausbau ist folgender: 
Ein MM für Instrumente und ein MM für Künstler. Im mm_kuenstler wird per Tags im Backend zugeordnet welcher Künstler welche Instrumente spielt.
Das Attribut ist eine Mehrfachauswahl aus die Tabelle Instrumente, Alias ist alis und Bezeichnung ist ein Textfeld (nicht übersetzt). Sortierung die ID. Keine wilde Sache eigentlich! 

Ich habe dazu schon mit DavidMaack gesprochen, konnten aber leider keine Lösung auf die Schnelle finden.

Habt ihr einen Tipp für mich, ob es an einer Einstellung liegen kann, oder ist das ein Fehler.

Viele Grüße

Markus Schindler

**Comment by discordier** [comment]
Anscheinend loest er das Value nicht korrekt zur Id bei dir auf.
Kann eine Einstellung sein, machst du bitte eben einen screenshot von deinem tag attribut?

**Comment by davidmaack** [comment]
![tags](https://cloud.githubusercontent.com/assets/988290/7046727/24716c2c-de08-11e4-8be6-bc9415e4638b.png)
Und hier noch mal der komplette StackTrace:
````
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3 (INSERT INTO tl_metamodel_tag_relation (att_id, item_id, value_sorting, value_id) VALUES (64,2,0,)) thrown in C:\xampp\htdocs\miraphone\system\modules\core\library\Contao\Database\Statement.php on line 279
#0 C:\xampp\htdocs\miraphone\system\modules\core\library\Contao\Database\Statement.php(250): Contao\Database\Statement->query()
#1 C:\xampp\htdocs\miraphone\system\modules\core\library\Contao\Database.php(185): Contao\Database\Statement->execute()
#2 C:\xampp\htdocs\miraphone\system\modules\metamodelsattribute_tags\classes\src\MetaModels\Attribute\Tags\AbstractTags.php(401): Contao\Database->execute('INSERT INTO tl_...')
#3 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\MetaModel.php(887): MetaModels\Attribute\Tags\AbstractTags->setDataFor(Array)
#4 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\MetaModel.php(923): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\Tags\Tags), Array, Array, 'de')
#5 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\MetaModel.php(1003): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), 'de', Array)
#6 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\Item.php(299): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#7 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\DcGeneral\Data\Driver.php(562): MetaModels\Item->save()
#8 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(611): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#9 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(668): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#10 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(775): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#11 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(750): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(138): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 C:\xampp\htdocs\miraphone\system\modules\symfony-event-dispatcher\classes\Symfony\Component\EventDispatcher\EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 C:\xampp\htdocs\miraphone\system\modules\symfony-event-dispatcher\classes\Symfony\Component\EventDispatcher\EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 C:\xampp\htdocs\miraphone\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 C:\xampp\htdocs\miraphone\system\modules\metamodels\classes\src\MetaModels\BackendIntegration\Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 C:\xampp\htdocs\miraphone\system\modules\core\classes\Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#20 C:\xampp\htdocs\miraphone\contao\main.php(137): Contao\Backend->getBackendModule('metamodel_mm_ku...')
#21 C:\xampp\htdocs\miraphone\contao\main.php(288): Main->run()
#22 {main}
````
In in setDataFor($arrValues) werden ja die Values als Array übergeben, hier ist irgendwie einer der Keys ein Leerstring ("") statt richtigerweise die ID des referenzierten Datensatzes. Daher fehlt dann auch beim SQL-Statement der Wert.

Wir haben testweise auch mal sie Einstellungen der Tags geändert (alles mal auf ID), geändert hat das aber irgendwie nix....

**Comment by discordier** [comment]
Was hast du denn als komplette Daten an die `setDataFor()`?
weiterhin, was macht die `widgetToValue()`bei dir? Ebenfalls bitte input und output dumpen.

**Comment by xantippe** [comment]
@codesache & @davidmaack noch aktuell?

**Comment by zonky2** [comment]
@codesache bitte mit aktuellem "MM" testen

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@codesache could you please have a final look at this and tell if your issue has been resolved?
