### ISSUE TITLE
Error if table tl_page and we use picker widget

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tags#61]
```
Warning: array_map(): Argument #2 should be an array in composer/vendor/metamodels/attribute_tags/src/MetaModels/Attribute/Tags/Tags.php on line 66
 
#0 [internal function]: __error(2, 'array_map(): Ar...', '/home/gutcert/c...', 66, Array)
#1 composer/vendor/metamodels/attribute_tags/src/MetaModels/Attribute/Tags/Tags.php(66): array_map('strval', '1027')
#2 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php(114): MetaModels\Attribute\Tags\Tags->valueToWidget(Array)
#3 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Model.php(175): MetaModels\DcGeneral\Data\Model->getProperty('tl_page')
...
```

**Comment by zonky2** [comment]
fixed in 2.0.1 https://github.com/MetaModels/attribute_tags/commit/efbc42244fcfc4e9bd3a2c7fd89c536bef519453#diff-8c81bfe3481dbd7775ed14aa86befcbaR62
